image: node:11.9

cache:
  paths:
    - node_modules/

pages:
  tags:
    - node:11.9
  script:
    - npm i
    - npm run build
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
      - public
    expire_in: 1 days
  only:
    - production